### ISSUE TITLE
Connecting to a remote SRT host

### ISSUE THREAD

**Issue by ripkk** [Cinegy/Cinegy.SRT#5]
Hi there,

I recently came across this wrapper library and let me first say thanks for the contribution.

I'm trying to connect to a remote linux server running a SRT listener using FFMPEG which looks something like this:

```
ffmpeg -i srt://0.0.0.0:9998?mode=listener&passphrase=somepassphrase
```

Current I push audio into that endpoint using a bash script on a client machince:

```
ffmpeg -i /some/audio.mp3 srt://{above_server_ip}:9998?mode=caller&passphrase=somepassphrase
```

There are more parameters in the FFMPEG command however its mainly for demonstration.

My question, would this be possbile to implement with the given wrapper at the moment? My goal would be to leave the server FFMPEG process running in `listener` mode and the C# app to push audio into that endpoint in `caller` mode.

 I did find a commented out line that allows you to set a passphrase:

` srt.srt_setsockflag_string(ns, SRT_STRING_SOCKOPT.SRTO_STRING_PASSPHRASE, "somepassphrase");`

I also tried binding to the remote server:

```
// Define a binding endpoint using the provided SRT port and bind the socket to it
var bindingEndPoint = new IPEndPoint(IPAddress.Parse("{above_server_ip}"), options.SrtPort);
srt.srt_bind(socket, bindingEndPoint).Validate("Binding listen socket");
```

Thanks for the help.

**Comment by BlackGad** [comment]
Certainly! The wrapper is essentially an automated conversion of the native **SRT API** using **SWIG**, with some enhancements for a more streamlined **C#** experience. If the native **SRT** library supports your desired functionality, then this wrapper should be able to handle it too.

To set up the passphrase and related encryption settings for the client socket before connecting, you can use the [SRTO_PASSPHRASE](https://github.com/Haivision/srt/blob/master/docs/API/API-socket-options.md#srto_passphrase), [SRTO_PBKEYLEN](https://github.com/Haivision/srt/blob/master/docs/API/API-socket-options.md#srto_pbkeylen), and [SRTO_CRYPTOMODE](https://github.com/Haivision/srt/blob/master/docs/API/API-socket-options.md#srto_cryptomode) options. Here's how you can do it:

```csharp
// Define the encryption mode:
// 0: SRT listener accepts any mode from the caller. SRT Caller or SRT Rendezvous will effectively use AES-CTR (1).
// 1: standard AES-CTR (without message integrity authentication).
// 2: AES-GCM mode with message integrity authentication (AEAD).
srt.srt_setsockflag_int(socket, SRT_INT_SOCKOPT.SRTO_INT_CRYPTOMODE, 0)
   .Validate("Setting encryption mode");

// Define the encryption key length:
// 0 = PBKEYLEN (default value)
// 16 = AES-128 (actual value)
// 24 = AES-192
// 32 = AES-256
srt.srt_setsockflag_int(socket, SRT_INT_SOCKOPT.SRTO_INT_PBKEYLEN, 32)
   .Validate("Setting encryption key length");

// Set the passphrase for encryption:
srt.srt_setsockflag_string(socket, SRT_STRING_SOCKOPT.SRTO_STRING_PASSPHRASE, "password")
   .Validate("Setting passphrase for encryption");
```

This should help you set up the necessary encryption settings for your C# application to push audio to the server endpoint in caller mode.

**Comment by ripkk** [comment]
Thanks @BlackGad I'll try this later and report back 🙂

I also had a follow up question in general, is it possible to not monitor a multicast IP and send direct MP3 encoded buffer stream? In my case I'm trying to push microphone audio using naudio wavebuffer to an srt endpoint. 

My audio and c# knowledge is very limited so any help would be appreciated. 👍

Please let me know if I should create a new issue for the above question.

Thanks again.

**Comment by BlackGad** [comment]
Hello,

Certainly, with the [SRT](https://en.wikipedia.org/wiki/Secure_Reliable_Transport) protocol, you have the flexibility to transfer any media data that the protocol supports. If you're looking to capture audio from a microphone, you can do so either as an uncompressed PCM stream or in encoded formats like AAC or MP3, which is essentially the MPEG-1/2 Audio format. Once captured, you can send this audio directly to an SRT listener. As simple example look to guidance on accessing microphone audio with C# using NAudio look [this](https://swharden.com/csdv/audio/naudio/) tutorial.

To address your specific query, there's no strict requirement to monitor a multicast IP. You can seamlessly send the MP3 encoded buffer stream from your microphone, leveraging the naudio wavebuffer, straight to your chosen SRT endpoint.

While this library offers a lot, it's primarily an SRT wrapper. For information beyond this scope, please refer to other appropriate resources. 
However, if you have any concerns or questions related to the wrapper itself, please don't hesitate to open a new issue.

Regards,
@BlackGad
