### ISSUE TITLE
Is thera a way to specify additional parameters in URL?

### ISSUE THREAD

**Issue by renta75** [Cinegy/Cinegy.SRT#7]
Like srt://172.25.8.139:8080?streamid=live.sls.com/live/test

**Comment by BlackGad** [comment]
Hi! I'm not entirely clear on the specific context of your question.

To better assist you, could you please clarify at what stage you are looking to pass and/or parse these additional parameters? Are you referring to the stage of setting up your connection or configuring your sender, or is your question more about how these parameters can be parsed by the receiver?

**Comment by BlackGad** [comment]
If you are looking for information on managing the `streamId` parameter in the SRT protocol, I recommend checking out the SRT API Socket Options documentation provided by Haivision on GitHub. This documentation covers various socket options, including `SRTO_STREAMID`, which should provide the detailed information you need for managing stream IDs in SRT. You can find this information at [Haivision's SRT GitHub Repository](https://github.com/Haivision/srt/blob/master/docs/API/API-socket-options.md).

**Comment by renta75** [comment]
I found the solution...

srt.srt_setsockflag_string(socket, SRT_STRING_SOCKOPT.SRTO_STRING_STREAMID, "live.sls.com/live/test");
