### ISSUE TITLE
Problem with the net 8.0

### ISSUE THREAD

**Issue by renta75** [Cinegy/Cinegy.SRT#8]
<img width="699" alt="image" src="https://github.com/Cinegy/Cinegy.SRT/assets/12384828/bcc82e7e-3749-4e93-a96d-f783785818c8">

**Comment by BlackGad** [comment]
Able to reproduce. Will look closely on this.

**Comment by BlackGad** [comment]
Issue fixed and pushed to [srt branch](https://github.com/Cinegy/srt/commit/e9fbd51edfebc7e44b01c9cce66df701df716456).
Use updated [SrtSharp](https://www.nuget.org/packages/SrtSharp/1.5.3.10064-alpha) NuGet package.
