### ISSUE TITLE
srt_listen_callback function is not faithful to original

### ISSUE THREAD

**Issue by superdanm2** [Cinegy/Cinegy.SRT#9]
In the libsrt documentation, it states that the callback function has the signature of:
int srt_listen_callback(SRTSOCKET lsn, srt_listen_callback_fn* hook_fn, void* hook_opaque);

Most notably, that it returns an integer, where 0 is successful and -1 is an error.

It also says that you can throw an exception in order to reject the request.

However, the C# wrapper wants a callback function that returns `void`, preventing the  integer functionality. A managed exception does not seem to produce the required result.

**Comment by BlackGad** [comment]
Managed code doesn’t follow the original unmanaged signatures exactly, but you can still get the functionality you need.

When dealing with the C# wrapper, throwing a managed exception will give a non-zero exit code on the unmanaged side. However, you can't replicate unmanaged exceptions directly in managed code. To reject a request, just dispose of the `clientSocket`.

It’s better not to throw managed exceptions in the callback. Instead, handle everything within the callback and close the connection if something goes wrong. Here’s how you might do it:

```csharp
private void ListenCallback(IntPtr opaque, int ns, int version, IPEndPoint address, string id)
{
    SRTSOCKET clientSocket = ns;
    try
    {
        if (string.IsNullOrEmpty(id)) id = "unspecified";

        Debug.WriteLine("CALLBACK: Client tries to connect from {0} with '{1}' id", address, id);

        // Validate password
        if (!string.IsNullOrWhiteSpace(Options.Password))
        {
            srt.srt_setsockflag_string(clientSocket, SRT_STRING_SOCKOPT.SRTO_STRING_PASSPHRASE, Options.Password)
                .Validate("Required pass phrase validation set");
        }

        // Custom validation goes here
        // ...

        // Keep the client socket for future use
	// Also here you can setup connection callback for client socket that will be triggered when connection brake.
    }
    catch (Exception e)
    {
        Debug.WriteLine("CALLBACK: Connection with a client from {0} with '{1}' id cannot be established. Details: {2}", address, id, e.Message);
        clientSocket.Dispose(); // Reject the connection
    }
}
```

By disposing of the `clientSocket` in the `catch` block, you effectively simulate the behavior of an unmanaged exception, thereby rejecting the connection in a controlled manner.

**Comment by superdanm2** [comment]
Thank you! This seems to work.

Just for closure on the managed exception topic:
Though I agree with you that throwing an exception is not ideal and I was only attempting it as some means to accomplish the goal, I want to reemphasize that it seems to go uncaught and get raised on a foreground thread I do not control and so doesn't seem viable. Maybe I'm wrong, but thought I'd provide you that feedback.
